environment:
  matrix:
  - nodejs_version: "14"
services:
  - mysql
install:
  - yarn
  - set PATH=%PATH%;C:\Program Files\MySql\MySQL Server 5.7\bin
before_test:
  - mysql -e "CREATE DATABASE IF NOT EXISTS `%DB_NAME%`;" --user=%DB_USER% --password=%DB_PASSWORD%
  - yarn global add sequelize-cli
  - sequelize db:migrate
test_script:
  - yarn test
build: off
